### Lab - Revisiting Machine Learning Case Study

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)

In [2]:
data = pd.read_csv('learningSet.csv')

C:\Users\Kate\AppData\Local\Temp\ipykernel_22424\3673836359.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('learningSet.csv')

In [3]:
#creating a categorical df:
categorical = data.select_dtypes([object])
categorical.head()

,OSOURCE,STATE,ZIP,MAILCODE,PVASTATE,NOEXCH,RECINHSE,RECP3,RECPGVG,RECSWEEP,MDMAUD,DOMAIN,CLUSTER,AGEFLAG,HOMEOWNR,CHILD03,CHILD07,CHILD12,CHILD18,GENDER,DATASRCE,SOLP3,SOLIH,MAJOR,GEOCODE,COLLECT1,VETERANS,BIBLE,CATLG,HOMEE,PETS,CDPLAY,STEREO,PCOWNERS,PHOTO,CRAFTS,FISHER,GARDENIN,BOATS,WALKER,KIDSTUFF,CARDS,PLATES,LIFESRC,PEPSTRFL,RFA_2,RFA_3,RFA_4,RFA_5,RFA_6,RFA_7,RFA_8,RFA_9,RFA_10,RFA_11,RFA_12,RFA_13,RFA_14,RFA_15,RFA_16,RFA_17,RFA_18,RFA_19,RFA_20,RFA_21,RFA_22,RFA_23,RFA_24,RFA_2R,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,GEOCODE2
0,GRI,IL,61081,,,0,,,,,XXXX,T2,36,,,,,,,F,,,,,,,,,,,,,,,,,,,,,,,,,X,L4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,L,E,X,X,X,C
1,BOA,CA,91326,,,0,,,,,XXXX,S1,14,E,H,,,,M,M,3,,,,2,,,,,,,,,,,,,,,,,,,,,L2G,A2G,A2G,A2G,A2G,A1E,A1E,A1E,A1E,A1E,A1E,,,,L1E,,,N1E,N1E,N1E,N1E,,F1E,L,G,X,X,X,A
2,AMH,NC,27017,,,0,,,,,XXXX,R2,43,,U,,,,,M,3,,,,,,,,,,,,,,,,,,,,,,,,X,L4E,S4E,S4E,S4E,S4E,S4F,S4F,S4F,,S4F,S4F,S4F,S4F,S4F,S4F,,S4D,S4D,,,S4D,S4D,S3D,L,E,X,X,X,C
3,BRY,CA,95953,,,0,,,,,XXXX,R2,44,E,U,,,,,F,3,,,,,,,,,,,,,,,,,,,,,,,,X,L4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,,S4E,S4E,S4E,S4E,S4E,S4E,S2D,S2D,A1D,A1D,A1D,A1D,,,L,E,X,X,X,C
4,,FL,33176,,,0,X,X,,,XXXX,S2,16,E,H,,,,,F,3,,12,,,,,Y,Y,,,,Y,,,Y,,Y,,Y,,Y,,3,,L2F,A2F,A2F,A2F,A1D,I2D,A1E,A1E,L1D,A1E,A1E,L1D,L3D,,L3D,A2D,A2D,A3D,A3D,A3D,I4E,A3D,A3D,L,F,X,X,X,A

In [4]:
#checking for NUll values in all the columns:
categorical.isna().sum()

OSOURCE       0
STATE         0
ZIP           0
MAILCODE      0
PVASTATE      0
NOEXCH        0
RECINHSE      0
RECP3         0
RECPGVG       0
RECSWEEP      0
MDMAUD        0
DOMAIN        0
CLUSTER       0
AGEFLAG       0
HOMEOWNR      0
CHILD03       0
CHILD07       0
CHILD12       0
CHILD18       0
GENDER        0
DATASRCE      0
SOLP3         0
SOLIH         0
MAJOR         0
GEOCODE       0
COLLECT1      0
VETERANS      0
BIBLE         0
CATLG         0
HOMEE         0
PETS          0
CDPLAY        0
STEREO        0
PCOWNERS      0
PHOTO         0
CRAFTS        0
FISHER        0
GARDENIN      0
BOATS         0
WALKER        0
KIDSTUFF      0
CARDS         0
PLATES        0
LIFESRC       0
PEPSTRFL      0
RFA_2         0
RFA_3         0
RFA_4         0
RFA_5         0
RFA_6         0
RFA_7         0
RFA_8         0
RFA_9         0
RFA_10        0
RFA_11        0
RFA_12        0
RFA_13        0
RFA_14        0
RFA_15        0
RFA_16        0
RFA_17        0
RFA_18        0
RFA_19        0
RFA_20        0
RFA_21        0
RFA_22        0
RFA_23        0
RFA_24        0
RFA_2R        0
RFA_2A        0
MDMAUD_R      0
MDMAUD_F      0
MDMAUD_A      0
GEOCODE2    132
dtype: int64

In [5]:
#It looks like there are no Nan values, but there are a lot of empty cells that is an equivalent. 
#We will replace empty spaces with Nan

In [6]:
categorical["MAILCODE"].value_counts()

     94013
B     1399
Name: MAILCODE, dtype: int64

In [7]:
categorical = categorical.apply(lambda x: x.replace(" ", np.NaN))

In [8]:
#checking for NUll values again and we are getting anotehr picture:
round(categorical.isna().sum()/len(categorical),4)*100

OSOURCE      0.97
STATE        0.00
ZIP          0.00
MAILCODE    98.53
PVASTATE    98.47
NOEXCH       0.01
RECINHSE    92.97
RECP3       97.89
RECPGVG     99.88
RECSWEEP    98.31
MDMAUD       0.00
DOMAIN       2.43
CLUSTER      2.43
AGEFLAG     30.97
HOMEOWNR    23.30
CHILD03     98.80
CHILD07     98.36
CHILD12     98.10
CHILD18     97.02
GENDER       3.10
DATASRCE    22.30
SOLP3       99.81
SOLIH       93.50
MAJOR       99.69
GEOCODE     84.02
COLLECT1    94.55
VETERANS    89.07
BIBLE       90.70
CATLG       91.76
HOMEE       99.07
PETS        84.99
CDPLAY      87.16
STEREO      86.59
PCOWNERS    89.02
PHOTO       94.98
CRAFTS      91.43
FISHER      92.53
GARDENIN    85.95
BOATS       97.87
WALKER      88.99
KIDSTUFF    98.39
CARDS       98.91
PLATES      99.41
LIFESRC     56.63
PEPSTRFL    52.55
RFA_2        0.00
RFA_3        2.04
RFA_4        2.42
RFA_5       35.21
RFA_6        3.73
RFA_7        9.30
RFA_8        3.68
RFA_9       11.79
RFA_10      34.32
RFA_11      10.92
RFA_12       9.35
RFA_13      42.15
RFA_14      19.77
RFA_15      68.63
RFA_16      21.40
RFA_17      28.98
RFA_18      22.29
RFA_19      25.67
RFA_20      52.61
RFA_21      36.91
RFA_22      26.88
RFA_23      58.98
RFA_24      38.75
RFA_2R       0.00
RFA_2A       0.00
MDMAUD_R     0.00
MDMAUD_F     0.00
MDMAUD_A     0.00
GEOCODE2     0.33
dtype: float64

In [9]:
#creating a new empty list and assigning 2 columns there:
drop_list = [cols for cols in categorical if cols in ["OSOURCE", "ZIP"]]
drop_list

['OSOURCE', 'ZIP']

In [10]:
#identifying columns with more than 85% of missing values and adding them to drop_list:
def get_null_columns(df, threshold=0.85):
    null_percentages = df.isnull().sum() / len(df)
    return list(null_percentages[null_percentages > threshold].index)

In [11]:
drop_list.extend(get_null_columns(categorical))
print(drop_list)

['OSOURCE', 'ZIP', 'MAILCODE', 'PVASTATE', 'RECINHSE', 'RECP3', 'RECPGVG', 'RECSWEEP', 'CHILD03', 'CHILD07', 'CHILD12', 'CHILD18', 'SOLP3', 'SOLIH', 'MAJOR', 'COLLECT1', 'VETERANS', 'BIBLE', 'CATLG', 'HOMEE', 'CDPLAY', 'STEREO', 'PCOWNERS', 'PHOTO', 'CRAFTS', 'FISHER', 'GARDENIN', 'BOATS', 'WALKER', 'KIDSTUFF', 'CARDS', 'PLATES']

In [12]:
#removing the columns included in a drop_list:
categorical_new = categorical.drop(columns=drop_list)

In [13]:
print(categorical.shape)
print(categorical_new.shape)

(95412, 74)
(95412, 42)

In [14]:
#working with Gender
categorical_new['GENDER'].value_counts()

F    51277
M    39094
U     1715
J      365
C        2
A        2
Name: GENDER, dtype: int64

In [15]:
categorical_new['GENDER'].unique()

array(['F', 'M', nan, 'C', 'U', 'J', 'A'], dtype=object)

In [16]:
categorical_new['GENDER'] = categorical_new['GENDER'].replace(" ", 'F')

In [17]:
categorical_new['GENDER'].value_counts()

F    51277
M    39094
U     1715
J      365
C        2
A        2
Name: GENDER, dtype: int64

In [18]:
df = pd.DataFrame(categorical_new["GENDER"].value_counts()).reset_index()

df.columns =["gender", "count"]
other = list(df[df["count"]< 2000]["gender"])

def clean_gender(x):
    if x in other:
        return "other"
    else:
        return x

categorical_new["GENDER"] = list(map(clean_gender, categorical_new["GENDER"]))

In [19]:
categorical_new['GENDER'].value_counts()

F        51277
M        39094
other     2084
Name: GENDER, dtype: int64

### Lab - Feature Engineering

In [20]:
#creating a numerical dataframe and droping target columns:
numerical = data.select_dtypes(np.number)
numerical = numerical.drop(columns = ['TARGET_B', 'TARGET_D'])
Y = data[['TARGET_B', 'TARGET_D']]

In [21]:
numerical.dtypes

ODATEDW       int64
TCODE         int64
DOB           int64
AGE         float64
NUMCHLD     float64
INCOME      float64
WEALTH1     float64
HIT           int64
MBCRAFT     float64
MBGARDEN    float64
MBBOOKS     float64
MBCOLECT    float64
MAGFAML     float64
MAGFEM      float64
MAGMALE     float64
PUBGARDN    float64
PUBCULIN    float64
PUBHLTH     float64
PUBDOITY    float64
PUBNEWFN    float64
PUBPHOTO    float64
PUBOPP      float64
MALEMILI      int64
MALEVET       int64
VIETVETS      int64
WWIIVETS      int64
LOCALGOV      int64
STATEGOV      int64
FEDGOV        int64
WEALTH2     float64
POP901        int64
POP902        int64
POP903        int64
POP90C1       int64
POP90C2       int64
POP90C3       int64
POP90C4       int64
POP90C5       int64
ETH1          int64
ETH2          int64
ETH3          int64
ETH4          int64
ETH5          int64
ETH6          int64
ETH7          int64
ETH8          int64
ETH9          int64
ETH10         int64
ETH11         int64
ETH12         int64
ETH13         int64
ETH14         int64
ETH15         int64
ETH16         int64
AGE901        int64
AGE902        int64
AGE903        int64
AGE904        int64
AGE905        int64
AGE906        int64
AGE907        int64
CHIL1         int64
CHIL2         int64
CHIL3         int64
AGEC1         int64
AGEC2         int64
AGEC3         int64
AGEC4         int64
AGEC5         int64
AGEC6         int64
AGEC7         int64
CHILC1        int64
CHILC2        int64
CHILC3        int64
CHILC4        int64
CHILC5        int64
HHAGE1        int64
HHAGE2        int64
HHAGE3        int64
HHN1          int64
HHN2          int64
HHN3          int64
HHN4          int64
HHN5          int64
HHN6          int64
MARR1         int64
MARR2         int64
MARR3         int64
MARR4         int64
HHP1          int64
HHP2          int64
DW1           int64
DW2           int64
DW3           int64
DW4           int64
DW5           int64
DW6           int64
DW7           int64
DW8           int64
DW9           int64
HV1           int64
HV2           int64
HV3           int64
HV4           int64
HU1           int64
HU2           int64
HU3           int64
HU4           int64
HU5           int64
HHD1          int64
HHD2          int64
HHD3          int64
HHD4          int64
HHD5          int64
HHD6          int64
HHD7          int64
HHD8          int64
HHD9          int64
HHD10         int64
HHD11         int64
HHD12         int64
ETHC1         int64
ETHC2         int64
ETHC3         int64
ETHC4         int64
ETHC5         int64
ETHC6         int64
HVP1          int64
HVP2          int64
HVP3          int64
HVP4          int64
HVP5          int64
HVP6          int64
HUR1          int64
HUR2          int64
RHP1          int64
RHP2          int64
RHP3          int64
RHP4          int64
HUPA1         int64
HUPA2         int64
HUPA3         int64
HUPA4         int64
HUPA5         int64
HUPA6         int64
HUPA7         int64
RP1           int64
RP2           int64
RP3           int64
RP4           int64
MSA         float64
ADI         float64
DMA         float64
IC1           int64
IC2           int64
IC3           int64
IC4           int64
IC5           int64
IC6           int64
IC7           int64
IC8           int64
IC9           int64
IC10          int64
IC11          int64
IC12          int64
IC13          int64
IC14          int64
IC15          int64
IC16          int64
IC17          int64
IC18          int64
IC19          int64
IC20          int64
IC21          int64
IC22          int64
IC23          int64
HHAS1         int64
HHAS2         int64
HHAS3         int64
HHAS4         int64
MC1           int64
MC2           int64
MC3           int64
TPE1          int64
TPE2          int64
TPE3          int64
TPE4          int64
TPE5          int64
TPE6          int64
TPE7          int64
TPE8          int64
TPE9          int64
PEC1          int64
PEC2          int64
TPE10         int64
TPE11         int64
TPE12         int64
TPE13         int64
LFC1          int64
LFC2          int64
LFC3          int64
LFC4          int64
LFC5          int64
LFC6          int64
LFC7          int64
LFC8          int64
LFC9          int64
LFC10         int64
OCC1          int64
OCC2          int64
OCC3          int64
OCC4          int64
OCC5          int64
OCC6          int64
OCC7          int64
OCC8          int64
OCC9          int64
OCC10         int64
OCC11         int64
OCC12         int64
OCC13         int64
EIC1          int64
EIC2          int64
EIC3          int64
EIC4          int64
EIC5          int64
EIC6          int64
EIC7          int64
EIC8          int64
EIC9          int64
EIC10         int64
EIC11         int64
EIC12         int64
EIC13         int64
EIC14         int64
EIC15         int64
EIC16         int64
OEDC1         int64
OEDC2         int64
OEDC3         int64
OEDC4         int64
OEDC5         int64
OEDC6         int64
OEDC7         int64
EC1           int64
EC2           int64
EC3           int64
EC4           int64
EC5           int64
EC6           int64
EC7           int64
EC8           int64
SEC1          int64
SEC2          int64
SEC3          int64
SEC4          int64
SEC5          int64
AFC1          int64
AFC2          int64
AFC3          int64
AFC4          int64
AFC5          int64
AFC6          int64
VC1           int64
VC2           int64
VC3           int64
VC4           int64
ANC1          int64
ANC2          int64
ANC3          int64
ANC4          int64
ANC5          int64
ANC6          int64
ANC7          int64
ANC8          int64
ANC9          int64
ANC10         int64
ANC11         int64
ANC12         int64
ANC13         int64
ANC14         int64
ANC15         int64
POBC1         int64
POBC2         int64
LSC1          int64
LSC2          int64
LSC3          int64
LSC4          int64
VOC1          int64
VOC2          int64
VOC3          int64
HC1           int64
HC2           int64
HC3           int64
HC4           int64
HC5           int64
HC6           int64
HC7           int64
HC8           int64
HC9           int64
HC10          int64
HC11          int64
HC12          int64
HC13          int64
HC14          int64
HC15          int64
HC16          int64
HC17          int64
HC18          int64
HC19          int64
HC20          int64
HC21          int64
MHUC1         int64
MHUC2         int64
AC1           int64
AC2           int64
ADATE_2       int64
ADATE_3     float64
ADATE_4     float64
ADATE_5     float64
ADATE_6     float64
ADATE_7     float64
ADATE_8     float64
ADATE_9     float64
ADATE_10    float64
ADATE_11    float64
ADATE_12    float64
ADATE_13    float64
ADATE_14    float64
ADATE_15    float64
ADATE_16    float64
ADATE_17    float64
ADATE_18    float64
ADATE_19    float64
ADATE_20    float64
ADATE_21    float64
ADATE_22    float64
ADATE_23    float64
ADATE_24    float64
CARDPROM      int64
MAXADATE      int64
NUMPROM       int64
CARDPM12      int64
NUMPRM12      int64
RDATE_3     float64
RDATE_4     float64
RDATE_5     float64
RDATE_6     float64
RDATE_7     float64
RDATE_8     float64
RDATE_9     float64
RDATE_10    float64
RDATE_11    float64
RDATE_12    float64
RDATE_13    float64
RDATE_14    float64
RDATE_15    float64
RDATE_16    float64
RDATE_17    float64
RDATE_18    float64
RDATE_19    float64
RDATE_20    float64
RDATE_21    float64
RDATE_22    float64
RDATE_23    float64
RDATE_24    float64
RAMNT_3     float64
RAMNT_4     float64
RAMNT_5     float64
RAMNT_6     float64
RAMNT_7     float64
RAMNT_8     float64
RAMNT_9     float64
RAMNT_10    float64
RAMNT_11    float64
RAMNT_12    float64
RAMNT_13    float64
RAMNT_14    float64
RAMNT_15    float64
RAMNT_16    float64
RAMNT_17    float64
RAMNT_18    float64
RAMNT_19    float64
RAMNT_20    float64
RAMNT_21    float64
RAMNT_22    float64
RAMNT_23    float64
RAMNT_24    float64
RAMNTALL    float64
NGIFTALL      int64
CARDGIFT      int64
MINRAMNT    float64
MINRDATE      int64
MAXRAMNT    float64
MAXRDATE      int64
LASTGIFT    float64
LASTDATE      int64
FISTDATE      int64
NEXTDATE    float64
TIMELAG     float64
AVGGIFT     float64
CONTROLN      int64
HPHONE_D      int64
RFA_2F        int64
CLUSTER2    float64
dtype: object

In [22]:
#checking for Null values in numerical columns:
get_null_columns(numerical, threshold=0)

['AGE',
 'NUMCHLD',
 'INCOME',
 'WEALTH1',
 'MBCRAFT',
 'MBGARDEN',
 'MBBOOKS',
 'MBCOLECT',
 'MAGFAML',
 'MAGFEM',
 'MAGMALE',
 'PUBGARDN',
 'PUBCULIN',
 'PUBHLTH',
 'PUBDOITY',
 'PUBNEWFN',
 'PUBPHOTO',
 'PUBOPP',
 'WEALTH2',
 'MSA',
 'ADI',
 'DMA',
 'ADATE_3',
 'ADATE_4',
 'ADATE_5',
 'ADATE_6',
 'ADATE_7',
 'ADATE_8',
 'ADATE_9',
 'ADATE_10',
 'ADATE_11',
 'ADATE_12',
 'ADATE_13',
 'ADATE_14',
 'ADATE_15',
 'ADATE_16',
 'ADATE_17',
 'ADATE_18',
 'ADATE_19',
 'ADATE_20',
 'ADATE_21',
 'ADATE_22',
 'ADATE_23',
 'ADATE_24',
 'RDATE_3',
 'RDATE_4',
 'RDATE_5',
 'RDATE_6',
 'RDATE_7',
 'RDATE_8',
 'RDATE_9',
 'RDATE_10',
 'RDATE_11',
 'RDATE_12',
 'RDATE_13',
 'RDATE_14',
 'RDATE_15',
 'RDATE_16',
 'RDATE_17',
 'RDATE_18',
 'RDATE_19',
 'RDATE_20',
 'RDATE_21',
 'RDATE_22',
 'RDATE_23',
 'RDATE_24',
 'RAMNT_3',
 'RAMNT_4',
 'RAMNT_5',
 'RAMNT_6',
 'RAMNT_7',
 'RAMNT_8',
 'RAMNT_9',
 'RAMNT_10',
 'RAMNT_11',
 'RAMNT_12',
 'RAMNT_13',
 'RAMNT_14',
 'RAMNT_15',
 'RAMNT_16',
 'RAMNT_17',
 'RAMNT_18',
 'RAMNT_19',
 'RAMNT_20',
 'RAMNT_21',
 'RAMNT_22',
 'RAMNT_23',
 'RAMNT_24',
 'NEXTDATE',
 'TIMELAG',
 'CLUSTER2']

In [23]:
#Cleaning GEOCODE2, WEALTH1, ADI, DMA,and MSA columns
#The first column is categorical, and the other 4 are numerical

In [24]:
categorical_new['GEOCODE2'].value_counts(dropna=False)

A      34484
B      28505
D      16580
C      15524
NaN      319
Name: GEOCODE2, dtype: int64

In [25]:
#Since the number of Nan is not very high, I will replace it with the most popular value - A
categorical_new['GEOCODE2'] = categorical['GEOCODE2'].fillna("A")

In [26]:
categorical_new['GEOCODE2'].value_counts(dropna=False)

A    34803
B    28505
D    16580
C    15524
Name: GEOCODE2, dtype: int64

In [29]:
print(numerical['WEALTH1'].value_counts(dropna=False))
numerical['WEALTH1'] = numerical["WEALTH1"].astype("object")

NaN    44732
9.0     7585
8.0     6793
7.0     6198
6.0     5825
5.0     5280
4.0     4810
3.0     4237
2.0     4085
1.0     3454
0.0     2413
Name: WEALTH1, dtype: int64

In [ ]:
#I think that for such a big number of Nan values it would be great to us KNN imputer, but with these number of columns 
# it is very time-consuming to cimpute it. Therefore I would use the mode in this case:

In [50]:
m_wealth1 = numerical['WEALTH1'].mode()
numerical['WEALTH1'] = numerical['WEALTH1'].fillna(m_wealth1)

In [51]:
numerical['WEALTH1'].value_counts(dropna=False)

9.0    52317
8.0     6793
7.0     6198
6.0     5825
5.0     5280
4.0     4810
3.0     4237
2.0     4085
1.0     3454
0.0     2413
Name: WEALTH1, dtype: int64

In [47]:
numerical['ADI'].value_counts(dropna=False)

13.0     7296
51.0     4622
65.0     3765
57.0     2836
105.0    2617
197.0    2075
109.0    2054
131.0    1978
67.0     1847
201.0    1772
107.0    1746
275.0    1717
233.0    1676
127.0    1651
329.0    1647
75.0     1588
241.0    1573
15.0     1472
83.0     1305
351.0    1193
111.0    1127
279.0    1075
213.0    1073
59.0     1000
157.0     996
129.0     955
181.0     924
281.0     863
0.0       843
367.0     813
271.0     807
577.0     773
263.0     745
335.0     696
63.0      686
209.0     669
179.0     656
455.0     645
291.0     634
337.0     613
269.0     611
215.0     602
245.0     597
315.0     585
71.0      582
221.0     576
307.0     573
203.0     558
133.0     554
277.0     548
77.0      542
319.0     506
383.0     501
301.0     488
427.0     472
53.0      422
199.0     413
17.0      413
113.0     412
187.0     411
303.0     409
321.0     406
177.0     393
243.0     392
451.0     392
361.0     388
211.0     385
173.0     366
175.0     365
185.0     358
61.0      356
207.0     354
235.0     348
89.0      345
425.0     337
339.0     330
69.0      327
459.0     324
205.0     320
353.0     319
237.0     308
115.0     305
373.0     305
249.0     301
381.0     292
91.0      290
73.0      288
119.0     278
331.0     274
371.0     269
423.0     269
421.0     267
323.0     263
325.0     259
645.0     257
217.0     255
393.0     253
355.0     251
412.0     250
359.0     247
413.0     246
219.0     243
247.0     240
389.0     239
87.0      231
93.0      230
445.0     226
405.0     223
117.0     220
327.0     217
409.0     215
403.0     211
313.0     210
433.0     205
391.0     205
229.0     197
435.0     192
448.0     185
165.0     181
429.0     175
253.0     164
462.0     163
439.0     152
457.0     146
227.0     143
417.0     142
437.0     141
342.0     140
363.0     138
419.0     136
NaN       132
441.0     128
469.0     126
295.0     125
257.0     125
467.0     122
473.0     120
415.0     119
621.0     118
39.0      117
251.0     116
283.0     112
317.0      99
299.0      93
613.0      91
431.0      85
265.0      83
379.0      81
465.0      78
377.0      73
255.0      72
591.0      71
183.0      69
471.0      68
9.0        68
159.0      68
55.0       66
231.0      64
85.0       64
625.0      63
443.0      58
375.0      56
603.0      49
195.0      48
305.0      46
449.0      45
297.0      40
293.0      40
19.0       37
95.0       37
273.0      35
3.0        29
627.0      28
11.0       25
385.0      25
21.0       18
121.0      13
25.0       13
35.0       11
149.0       9
123.0       8
151.0       8
135.0       7
285.0       7
29.0        7
43.0        6
47.0        5
141.0       5
345.0       5
143.0       4
153.0       4
31.0        4
357.0       3
33.0        3
140.0       3
139.0       2
145.0       2
287.0       2
45.0        2
261.0       2
651.0       1
103.0       1
601.0       1
161.0       1
147.0       1
Name: ADI, dtype: int64

In [54]:
#replacing NAn with mean:
m_adi = numerical["ADI"].median()
numerical['ADI'] = numerical['ADI'].fillna(m_adi)

In [48]:
numerical['DMA'].value_counts(dropna=False)

803.0    7296
602.0    4632
807.0    3765
505.0    2839
819.0    2588
539.0    2222
524.0    2079
623.0    2009
862.0    1847
753.0    1780
618.0    1772
613.0    1717
528.0    1651
534.0    1647
820.0    1638
609.0    1583
751.0    1566
825.0    1472
527.0    1316
560.0    1175
617.0    1127
517.0    1085
567.0    1073
563.0    1000
616.0     993
548.0     955
659.0     917
518.0     863
790.0     813
641.0     788
804.0     773
650.0     754
561.0     690
513.0     661
640.0     656
839.0     645
529.0     641
881.0     640
770.0     635
671.0     611
622.0     597
557.0     588
866.0     582
571.0     567
678.0     565
630.0     564
789.0     548
635.0     547
658.0     542
648.0     512
693.0     511
686.0     501
652.0     488
619.0     481
744.0     449
575.0     436
669.0     435
632.0     424
588.0     422
540.0     414
855.0     413
752.0     403
541.0     397
679.0     394
612.0     387
546.0     387
801.0     386
682.0     384
637.0     363
675.0     363
649.0     363
551.0     356
868.0     345
507.0     343
691.0     337
810.0     330
828.0     327
545.0     324
625.0     320
811.0     320
570.0     312
813.0     308
718.0     305
705.0     302
716.0     301
509.0     290
800.0     288
676.0     286
709.0     283
610.0     278
722.0     273
765.0     271
519.0     269
520.0     266
670.0     259
724.0     253
698.0     250
530.0     247
503.0     245
531.0     245
515.0     244
725.0     240
692.0     240
634.0     229
581.0     227
757.0     221
628.0     217
702.0     216
522.0     215
627.0     214
605.0     205
550.0     204
624.0     202
600.0     199
604.0     198
636.0     192
0.0       187
673.0     181
611.0     181
642.0     176
603.0     175
743.0     169
717.0     157
687.0     156
633.0     150
656.0     148
756.0     146
762.0     142
651.0     141
553.0     140
746.0     138
525.0     135
NaN       132
662.0     128
657.0     128
564.0     125
764.0     124
802.0     122
592.0     118
771.0     117
606.0     113
758.0     108
544.0     107
643.0     104
773.0      97
755.0      93
754.0      91
759.0      87
710.0      81
737.0      80
767.0      80
638.0      76
711.0      73
644.0      72
821.0      71
734.0      71
501.0      68
647.0      67
639.0      66
547.0      66
620.0      64
582.0      64
736.0      61
661.0      58
631.0      58
760.0      56
646.0      49
766.0      40
511.0      38
745.0      38
542.0      37
626.0      36
749.0      35
506.0      29
583.0      28
504.0      25
740.0      23
512.0      18
535.0      13
533.0      13
510.0      11
532.0       9
556.0       8
500.0       8
523.0       8
508.0       7
514.0       7
566.0       6
798.0       6
573.0       5
555.0       5
521.0       5
549.0       4
536.0       4
577.0       4
537.0       3
574.0       3
565.0       3
543.0       2
538.0       2
598.0       2
502.0       2
569.0       1
554.0       1
584.0       1
552.0       1
516.0       1
Name: DMA, dtype: int64

In [56]:
#replacing NAn with mean:
m_dma = numerical["DMA"].median()
numerical['DMA'] = numerical['DMA'].fillna(m_dma)

In [49]:
numerical['MSA'].value_counts(dropna=False)

0.0       21333
4480.0     4606
1600.0     4059
2160.0     2586
520.0      1685
6780.0     1525
5945.0     1500
7320.0     1472
7600.0     1457
3360.0     1414
6200.0     1409
8280.0     1378
7040.0     1360
5775.0     1255
1920.0     1217
5120.0     1195
6440.0     1076
7360.0     1046
2080.0      993
7400.0      929
6920.0      894
5000.0      824
3760.0      817
5960.0      791
3480.0      790
2680.0      771
5080.0      745
4120.0      722
1520.0      697
3120.0      691
8960.0      644
7240.0      619
6640.0      592
2800.0      584
3000.0      560
3600.0      543
5360.0      523
5880.0      507
640.0       487
5560.0      478
8520.0      474
3160.0      465
4920.0      456
4520.0      444
7510.0      427
8735.0      415
8200.0      395
7160.0      389
1000.0      387
3840.0      382
8560.0      363
2960.0      354
200.0       353
3320.0      341
2020.0      339
2840.0      334
7500.0      334
5920.0      333
440.0       311
8720.0      298
680.0       288
4900.0      286
2700.0      270
1720.0      261
3720.0      255
3980.0      250
1760.0      250
2640.0      247
9040.0      246
7480.0      241
1560.0      240
760.0       235
7840.0      233
4040.0      231
6120.0      227
6880.0      226
1440.0      223
8120.0      222
600.0       213
2400.0      211
2710.0      208
4400.0      208
2760.0      208
2320.0      206
840.0       203
4720.0      201
5790.0      198
3660.0      198
7080.0      195
4280.0      191
6080.0      187
460.0       186
6960.0      183
1960.0      183
5160.0      182
1640.0      177
5170.0      177
7120.0      175
7460.0      172
6720.0      169
2120.0      168
3440.0      164
3560.0      164
1080.0      161
2560.0      158
2440.0      157
480.0       157
7520.0      156
7680.0      156
4680.0      153
2240.0      153
5240.0      153
1150.0      152
920.0       151
3290.0      150
7920.0      146
1880.0      144
1620.0      143
5345.0      143
9200.0      140
3810.0      139
2580.0      136
1125.0      133
NaN         132
4890.0      132
7485.0      130
5330.0      128
8780.0      127
5910.0      127
1800.0      125
3880.0      125
6580.0      124
7800.0      123
6690.0      123
6600.0      122
2920.0      121
380.0       120
6740.0      112
7880.0      110
8240.0      108
3080.0      105
4880.0      101
5800.0      101
870.0        98
7490.0       98
1400.0       98
1360.0       97
2670.0       97
2750.0       96
3520.0       96
1145.0       92
2900.0       91
4600.0       90
9260.0       89
3960.0       87
860.0        86
3800.0       84
3920.0       83
1240.0       82
5200.0       82
320.0        82
8320.0       81
4360.0       80
6015.0       79
4420.0       79
2720.0       78
8440.0       78
8640.0       78
6895.0       77
2995.0       77
9270.0       76
7720.0       74
3710.0       74
4940.0       73
1040.0       72
1660.0       72
880.0        72
6560.0       71
9340.0       70
8800.0       70
2620.0       68
3060.0       68
2520.0       66
2330.0       66
9360.0       66
3620.0       65
8600.0       64
6980.0       64
2040.0       63
4100.0       63
3400.0       63
2180.0       61
3870.0       60
2290.0       59
1740.0       59
4200.0       59
3150.0       59
3850.0       58
9080.0       57
3740.0       57
6520.0       56
2655.0       55
1580.0       55
6820.0       55
500.0        55
8940.0       54
2980.0       53
3605.0       53
1020.0       53
40.0         52
8920.0       51
7000.0       51
5280.0       49
7760.0       49
450.0        49
220.0        48
120.0        48
5990.0       47
3350.0       47
8360.0       47
7640.0       45
2650.0       44
1260.0       44
3500.0       44
7200.0       43
3580.0       43
1010.0       42
3040.0       41
7620.0       41
2030.0       41
6660.0       39
2200.0       38
8140.0       37
4150.0       36
8750.0       36
8840.0       36
4080.0       34
2985.0       33
1350.0       32
6240.0       32
2880.0       31
3285.0       29
1123.0       26
5720.0       25
5600.0       24
2340.0       22
6340.0       22
3700.0       21
720.0        17
6160.0       17
5483.0       13
5380.0       11
1840.0       11
2000.0        9
1680.0        7
6280.0        7
160.0         6
6760.0        6
5190.0        6
3283.0        5
1280.0        5
5640.0        5
9160.0        4
560.0         4
8400.0        4
8160.0        3
6483.0        3
2281.0        3
875.0         3
3240.0        3
5523.0        3
7560.0        3
6403.0        3
4000.0        2
733.0         2
6840.0        2
1303.0        2
7610.0        2
9320.0        2
6800.0        2
3680.0        2
5015.0        2
80.0          2
960.0         1
1480.0        1
1950.0        1
6323.0        1
5660.0        1
3180.0        1
1320.0        1
8003.0        1
1540.0        1
2975.0        1
9000.0        1
9140.0        1
3200.0        1
9280.0        1
743.0         1
8480.0        1
Name: MSA, dtype: int64

In [57]:
#replacing NAn with mean:
m_msa = numerical["MSA"].median()
numerical['MSA'] = numerical['MSA'].fillna(m_msa)